### ISSUE TITLE
Still not right version

### ISSUE THREAD

**Issue by ghost** [jrbudda/CitizensUI#4]
That didn't work. CitizensUI still comes up as 0.8.0.2. I noticed that the version releases in the zip are one version behind the name of the zip. ex. citizensUI0.8.0.3.zip contains 0.8.0.2. citizens 0.8.0.2.zip contains 0.8.0.1

**Comment by jrbudda** [comment]
Ya know what it is.... Github doesn't update the file if you upload a new one with the same name. The zip I uploaded was correct, but it sends the wrong file on download. Try now.

**Comment by ghost** [comment]
that did the trick. thank you
