### ISSUE TITLE
Sentry Stats

### ISSUE THREAD

**Issue by ghost** [jrbudda/CitizensUI#5]
When the ui brings up the stats (ie. HP, strength, armor etc.) it does so correctly, however, the stats do not save correctly. If I modify them in the manually they will load correctly on next load. If I modify them in the ui and save, next load does not reflect changes. I checked and it does not modify the save file.

**Comment by jrbudda** [comment]
Cant seem to duplicate this problem. Checking the saves.yml after saving reflects the changes i make in the UI for sentry.

Make sure you're not editing the file with the server running. Calling stop I think saves over the yml file with whatever is loaded on the server.

**Comment by ghost** [comment]
You are correct, thank you. Another thing i noticed though in the scripts.yml in denizen/scripts folder. Before editing with CitizensUI it reads - FLAG 'INFOBOOTHINFO:PROMOTED' 'DURATION:15' after edit and save - FLAG INFOBOOTHINFO:PROMOTED' 'DURATION:15 . The missing single quotes are breaking the code causing the denizen to no longer respond to chat commands. I appologize if I'm being a bother

**Comment by jrbudda** [comment]
I will look into this, although in general you do not need quotes at all unless your flag value has a space in it. Duration modifiers never need quotes.

**Comment by ghost** [comment]
You are correct sir. I manually removed the quotes, reloaded the ui and resaved. This resulted in a working denizen. thank you.
