### ISSUE TITLE
NPC id option

### ISSUE THREAD

**Issue by ghost** [jrbudda/CitizensUI#6]
Recently Citizens 2 updated to 2.0.1. When they did this, the NPC id option for assignments output no longer works. If I changed the option to assign by name and all was ok. Do you know if assignment by NPCID is still possible?

**Comment by jrbudda** [comment]
According to aufdemrand, assignment by ID has not actually been implemented yet in Denizen... are you sure it was actually working before?

**Comment by ghost** [comment]
Yes quite positive. Prior to the update it was allowing me to assign the scripts using the NPCID option. However, After the release of citizens 2.0.1 it stopped functioning that way and I had to change it to the NPC name to make it work again.
